Majik/config/routes.rb
Rails.application.routes.draw do
  get 'home_page/home'

  get 'home_page/help'

  get 'home_page/about'

  devise_for :users
  resources :images
  root "home_page#home"

end

Majik/app/models/filter.rb
class Filter < ActiveRecord::Base
end

Majik/app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image_path, ImagePathUploader # Tells rails to use this uploader for this model.
    validates :image_name, presence: true # Make sure the owner's name is present.
end

Majik/app/models/user.rb
class User < ActiveRecord::Base
  has_many :images
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Majik/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: [:edit,:new,:update,:destroy]
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:user_name]
  end
end

Majik/app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def home
  	@images = Image.paginate(page: params[:page], per_page: 3)
  end

  def help
  end

  def about
  end
end

Majik/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    #@images = Image.all
    @images = Image.paginate(page: params[:page], per_page: 5)
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to images_path, notice: "The image #{@image.image_name} has been uploaded."
    else
      render "new"
    end
    #respond_to do |format|
    #  if @image.save
    #    format.html { redirect_to @image, notice: 'Image was successfully created.' }
    #    format.json { render :show, status: :created, location: @image }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @image.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path, notice:  "The image #{@image.image_name} has been deleted."
    #@image.destroy
    #respond_to do |format|
    #  format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
    #  format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image_name, :parent_id, :user_id, :version, :image_path, :filter_id)
    end
end

Majik/app/helpers/application_helper.rb
module ApplicationHelper
end

Majik/app/helpers/home_page_helper.rb
module HomePageHelper
end

Majik/app/helpers/images_helper.rb
module ImagesHelper
end

Majik/app/views/home_page/about.html.erb
<h1>HomePage#about</h1>
<p>Find me in app/views/home_page/about.html.erb</p>

Majik/app/views/home_page/help.html.erb
<h1>HomePage#help</h1>
<p>Find me in app/views/home_page/help.html.erb</p>

Majik/app/views/home_page/home.html.erb
<% if signed_in? %>
<div class="row">
  <aside class="span4">
    <section>
    </br>
      <h1>
         My Name: <%= current_user.user_name %></br>
             My Email: <%= current_user.email %></br>
             My Images:<%= Image.count %></br>
             My Friends:<%= 0 %></br>
             My Filters:<%= 0 %></br>
         
      </h1>
    </section>
  </aside>

  <div class="span8">
     <h3>Images (<%= Image.count %>)</h3>
      <%= will_paginate @images %>

      <span class="content">
      	<% @images.each do |image| %>
      	<td><%= image_tag image.image_path,size:"600"%></td>
      	<td></br></td>
      	<td></br></td>
      	<td></br></td>

      	<% end %>
      </span>

      <%= will_paginate @images %>
  </div>
</div>




<%else%>
<div class="center hero-unit">
  <h1>Welcome to Majik</h1>
  <h2>
    This is the home page for Majik.
  </h2>
  <div><%= link_to image_tag("1.jpg", alt: "Majik"), root_path %></div>
</br>

  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large" %>
</div>
<%end%>

Majik/app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_name %><br>
    <%= f.text_field :image_name %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :image_path %><br>
    <%= f.text_field :image_path %>
  </div>
  <div class="field">
    <%= f.label :filter_id %><br>
    <%= f.number_field :filter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Majik/app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

Majik/app/views/images/home.html.erb
<h1>Home Page</h1>

Majik/app/views/images/index.html.erb
<h1>My Images</h1>

<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>

<%= link_to "Upload Image", new_image_path, class: "btn "%>
<%= will_paginate %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Image</th>
      <th>Image Name</th>
      <th>Image Version</th>
      <th>Image Tag</th>
      <th>Image Filter</th>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image_tag image.image_path,size:"400"%></td>
        <td><%= image.image_name %></td>
        <td><%= image.version %></td>
        <td><%= 'null' %></td>
        <td><%= image.filter_id %></td>
        <td><%= link_to "Download image", image.image_path_url %></td>
        <td><%= button_to "Delete",  image, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{image.image_name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

Majik/app/views/images/new.html.erb
<h1>New image</h1>

<% if !@image.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="well">
  <%= form_for @image, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :image_name %>
    <%= f.label :imagepath %>
    <%= f.file_field :image_path %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

Majik/app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image name:</strong>
  <%= @image.image_name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @image.parent_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @image.user_id %>
</p>

<p>
  <strong>Version:</strong>
  <%= @image.version %>
</p>

<p>
  <strong>Image path:</strong>
  <%= @image.image_path %>
</p>

<p>
  <strong>Filter:</strong>
  <%= @image.filter_id %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

Majik/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Majik</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Majik", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">     
          <% if signed_in? %>            
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Friends", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= Images %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Images", images_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Create Images",'#' %></li>
                <li class="divider"></li>
                <li><%= link_to "Upload Images", new_image_path %></li>       
              </ul>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= 'Filters' %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Filters", '#' %></li>
                <li class="divider"></li>
                <li><%= link_to "Upload Filters", '#' %></li>        
              </ul>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Account", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", home_page_about_path %></li>
            <li><%= link_to "Help", home_page_help_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>
<div class="container">
<%= yield%>
</div>
</body>
</html>